name: CLA Validator
on: pull_request
env:
  DOC_BUILD_TYPE: stage
  CLA_GITHUB_TOKEN: ${{ secrets.CLA_GITHUB_TOKEN }}
  CLA_GIST_FILE: ${{ secrets.CLA_GIST_FILE }}
jobs:
  state_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node index.js ${{ github.repository }} ${{ github.event.number }}