name: CLA Validator
on: pull_request
env:
  CLA_GITHUB_TOKEN: ${{ secrets.CLA_GITHUB_TOKEN }}
  CLA_GIST_FILE: ${{ secrets.CLA_GIST_FILE }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node index.js ${{ github.repository }} ${{ github.event.number }}
      - name: failed
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Please sign the [CLA](https://cla-assistant.io/${{ github.repository }}) first, and then comment `I have signed the cla` again under this pull request.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}